image: trevorlbrooks/stoutpipeline 
cache:
    paths:
    

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ce/ci/services/README.html for examples.
services:
    - mysql:5.7
# Set any variables we need
variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_DATABASE: StOut
    MYSQL_ROOT_PASSWORD: mysql

backend:
    tags:
        -  test
    before_script:
        - cd backend/stout
        - mvn clean install
    script:
        - "" 
frontend:
    tags:
        - test
    before_script: 
      - cd webapp
    script:
        - ""
