image: trevorlbrooks/stoutpipeline 
cache:
    paths:
      - node_modules/    

stages:
  - test

# Set any variables we need
variables:
    # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
    MYSQL_DATABASE: StOut
    MYSQL_ROOT_PASSWORD: mysql

backend:
    image: maven:latest
    stage: test
    services:
      - mysql:5.7
    tags:
        -  test
    before_script:
        - cd backend/stout
        - mvn clean install
    script:
        - mvn test 
frontend:
    stage: test
    tags:
        - test
    before_script: 
      - cd webApp
      - npm install bower phantomjs-prebuilt 
      - npm install
      - bower install --allow-root
    script:
        - npm test
