service: katie.mtech.edu/tbrooks/StOut/backend
casURL: https://mtlbsso.mtech.edu/idp/profile/cas/login

logging:
  level: INFO
  loggers:
    edu.mtech.stout: DEBUG

database:
  driverClass: com.mysql.jdbc.Driver 
  user: stout
  password: pass?
  url: jdbc:mysql://localhost:3306/Stout

