service: katie.mtech.edu/tbrooks/StOut/backend
casURL: https://mtlbsso.mtech.edu/idp/profile/cas/login

logging:
  level: INFO
  loggers:
    edu.mtech.stout: DEBUG
  appenders:
    - type: file
      currentLogFileName: ./logs/stout.log
      #date and compress logs for previous days.
      archivedLogFilenamePattern: ./logs/stout-%d.log.gz
      archivedFilecount: 5
      timeZone: UTC

database:
  driverClass: com.mysql.jdbc.Driver 
  user: stout
  password: pass?
  url: jdbc:mysql://localhost:3306/Stout

